# Use the official Python runtime as a base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Initialize the database
RUN flask db init  
RUN flask db migrate  
RUN flask db upgrade  

# Add the application code to the container
ADD . /app

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define the command to run application
CMD flask run -h 0.0.0.0 -p 5000
